// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_day_20 = "CgkI5PnH0d0WEAIQBQ"; // <GPGSID>
        public const string achievement_saving_throw = "CgkI5PnH0d0WEAIQCA"; // <GPGSID>
        public const string achievement_day_10 = "CgkI5PnH0d0WEAIQBA"; // <GPGSID>
        public const string leaderboard_14_day_score = "CgkI5PnH0d0WEAIQCg"; // <GPGSID>
        public const string achievement_3_of_a_kind = "CgkI5PnH0d0WEAIQAw"; // <GPGSID>
        public const string leaderboard_28_day_score = "CgkI5PnH0d0WEAIQCw"; // <GPGSID>
        public const string achievement_month_at_sea = "CgkI5PnH0d0WEAIQBg"; // <GPGSID>
        public const string leaderboard_7_day_score = "CgkI5PnH0d0WEAIQCQ"; // <GPGSID>
        public const string achievement_3_fish_small_to_big = "CgkI5PnH0d0WEAIQAg"; // <GPGSID>
        public const string achievement_dine_on_turtle_soup = "CgkI5PnH0d0WEAIQBw"; // <GPGSID>
        public const string achievement_3_fish_big_to_small = "CgkI5PnH0d0WEAIQAA"; // <GPGSID>

}

